name: "Hello"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  plan:
    runs-on: self-hosted
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - run: echo "Hello dem0"
      - run: env | grep "CODEBUILD"
