name: "Push"
on:
  push:
    branches:
      - main
jobs:
  plan:
    runs-on: self-hosted
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - run: echo "Hello demo"
      - run: env | grep "CODEBUILD"
