name: "Submit to CodeBuild"
on:
  workflow_run:
    workflows: ["Push"]
jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fortum-vaanavil/gh-runner-codebuild@9cb42594ea1cd7d4be54090ed5e4baa38408766d
        with:
          github-token: ${{ secrets.PAT }}
          project-name: github-actions
