name: "Submit to CodeBuild"
on:
  workflow_run:
    workflows: ["Push"]
jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fortum-vaanavil/gh-runner-codebuild@06ebaf5d104ef2069a3cebfb91d6ab18dd84f0bc
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        with:
          github-token: ${{ secrets.PAT }}
          project-name: github-actions
