name: "Submit to CodeBuild"
on:
  workflow_run:
    workflows: ["Push"]
jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v5
        with:
          script: |
            const script = require('./get-jobs.js')
            console.log(await script({github, context}))
